[package]
name = "contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }

[[target.starknet-contract]]
casm = true

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.34.0" }
assert_macros = "2.9.1"

[scripts]
test = "snforge test"
